import os

from env_util import parse_bool, parse_float, parse_positive_int

DEFAULT_STATIC_MAX_WORKERS = 8
DEFAULT_DYNAMIC_MAX_WORKERS = 2
DEFAULT_STATIC_CONFIDENCE_THRESHOLD = 0.55

SCRAPE_STATIC_MAX_WORKERS = parse_positive_int(
    os.getenv("SCRAPE_STATIC_MAX_WORKERS"),
    DEFAULT_STATIC_MAX_WORKERS,
)
SCRAPE_DYNAMIC_MAX_WORKERS = parse_positive_int(
    os.getenv("SCRAPE_DYNAMIC_MAX_WORKERS"),
    DEFAULT_DYNAMIC_MAX_WORKERS,
)
SCRAPE_STATIC_CONFIDENCE_THRESHOLD = parse_float(
    os.getenv("SCRAPE_STATIC_CONFIDENCE_THRESHOLD"),
    DEFAULT_STATIC_CONFIDENCE_THRESHOLD,
    minimum=0,
    maximum=1,
)
SCRAPE_DYNAMIC_ENABLED = parse_bool(os.getenv("SCRAPE_DYNAMIC_ENABLED"), True)
